### ISSUE TITLE
`---` at the beginning/end causes a crash

### ISSUE THREAD

**Issue by snugghash** [maaslalani/slides#77] opened 2021-07-08 16:29 UTC
**Describe the bug**
`---` at the beginning causes a crash. Overall, low prio bug.

**To Reproduce**
1. 
```slides.md
---

# second slide
---
```
2. slides slides.md
3. Crash

**Expected behavior**
One empty slide

**Logs**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x151c7c5]

goroutine 1 [running]:
github.com/maaslalani/slides/internal/model.(*Model).Load(0xc00089fc18, 0x1355c71, 0x1d86440)
	github.com/maaslalani/slides/internal/model/model.go:83 +0x165
github.com/maaslalani/slides/cmd.glob..func1(0x1d6f640, 0xc00042baf0, 0x1, 0x1, 0x0, 0x0)
	github.com/maaslalani/slides/cmd/root.go:38 +0x125
github.com/spf13/cobra.(*Command).execute(0x1d6f640, 0xc0000be010, 0x1, 0x1, 0x1d6f640, 0xc0000be010)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x1d6f640, 0xc000000180, 0x200000003, 0xc000000180)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/maaslalani/slides/cmd.Execute()
	github.com/maaslalani/slides/cmd/root.go:50 +0x31
main.main()
	github.com/maaslalani/slides/main.go:8 +0x25

**Comment by marcotrosi** [comment] 2021-07-08 18:49
I had the same issue yesterday and today I was not able to reproduce it, but with your example shown above I get the same error again. I also had very few lines in the markdown file. I'll try again maybe I can make it crash again with the lines I had yesterday.

**Comment by marcotrosi** [comment] 2021-07-08 18:56
okay maybe I also had the 3 dashes before my first heading. But I don't remember.
But I can confirm, the following will crash
```
---
# foo
```

and this not
```
---
# foo
bar
```

**Comment by snugghash** [comment] 2021-07-08 22:54
Related to the above I think,
```
# asdf
## subheadline
```
Fails to generate the top headline.
```
# asdf
a
## subheadline
```
Generates both

**Comment by maaslalani** [comment] 2021-07-08 23:03
Thanks for reporting this, going to look into it today. I believe this is a very subtle bug with how we parse for our custom themes in the first slides. Users can pass configuration as YAML as the first "slide" to customize their themes. And if it is valid YAML we try to parse the first slide. I believe because (unfortunately) markdown's headers are the same as YAML comments they parse as valid. Which would explain why adding a line (normal text) makes everything work.

**Comment by maaslalani** [comment] 2021-07-09 01:42
This PR should fix the issues: https://github.com/maaslalani/slides/pull/79

**Comment by maaslalani** [comment] 2021-07-11 20:51
This PR fixes the issues and is now merged into the `main` branch
  https://github.com/maaslalani/slides/pull/81

**Closed by maaslalani** 2021-07-11 20:51 UTC
