### ISSUE TITLE
Incrementally show items / bullet points of a page

### ISSUE THREAD

**Issue by christianparpart** [maaslalani/slides#196] opened 2022-11-04 17:39 UTC
**Is your feature request related to a problem? Please describe.**

Yes, I want to create a presentation that I can talk along to. I do not want the full page to be shown when sliding to it but only show up to a certain marker, and then be able to press a key (say `j` etc) to incrementally populate the page with each new part (e.g. bullet point or paragraph) that is to be shown.

**Describe the solution you'd like**

What I can think of is to use line markers, just like `---` for pagination. But that would only work on a paragraph level AFAIK and probably a more sophisticated solution should be chosen, a string delimiter that can be anywhere in a line, even multiple times in a single line. That way it would be possible to incrementally populate/show the page as one talks along with it. This would especially also work with incrementally showing more bullet points.

**Describe alternatives you've considered**

Using MS PowerPoint? No, I don't think anything terminal related does support that yet. But for getting `slides` into more serious use, I can see a great benefit in that.

**Additional context**

Finding a marker might be hard and I don't want to mandate anything here. Anything that's distinguishable from the actual content and yet easy to type and read at the end of the lines where a split ought to happen. e.g. what about `^^^` (I doubt that'll rarely happen that someone wants to write that).

p.s.: whatever marker is decided to be taken, code blocks should not be subject to be split up (or should then?). 🤔

**Comment by maaslalani** [comment] 2022-11-04 20:31
Hey I believe this is a duplicate of #177 (feel free to reopen this issue if I am mistaken)

**Closed by maaslalani** 2022-11-04 20:31 UTC

**Comment by maaslalani** [comment] 2023-12-31 05:45
Proposal to fix: https://github.com/maaslalani/slides/pull/276#issuecomment-1872677592
