### ISSUE TITLE
Date metadata seems to print binary representation of number

### ISSUE THREAD

**Issue by ariary** [maaslalani/slides#105] opened 2021-10-01 14:35 UTC
**Describe the bug**
The date is not well rendering and it seems that the output is in fact the binary representation of the number or something related.

**To Reproduce**
1. Fill metadata in your markdown:
```
--- 
author: toto
date: October 3, 2021
paging: Page %d / %d
--- 
```
2. Launch your slide 

**Expected behavior**
The date will appears as: `October 10, 10110 `

**Desktop (please complete the following information):**
 - OS: Linux kali 5.4.0-kali3-amd64

**Comment by maaslalani** [comment] 2021-10-01 14:58
Date actually accepts a `date` format using the date `January 2, 2006`.

If you change your metadata to:

```
--- 
author: toto
date: January 2, 2006
paging: Page %d / %d
--- 
```

Everything should work as you expect.

**Comment by maaslalani** [comment] 2021-10-01 14:59
I agree though this is a little bit confusing, we should probably make a way to double check that the date is `2006-01-02` or start using our own custom format like `YYYY-MM-DD` so its less confusing.

**Comment by maaslalani** [comment] 2021-10-01 15:10
The root cause of this is https://github.com/maaslalani/slides/issues/106. I will close this issue since https://github.com/maaslalani/slides/issues/105#issuecomment-932303910 should unblock you but https://github.com/maaslalani/slides/issues/106 is the longer term solution.

**Closed by maaslalani** 2021-10-01 15:10 UTC
