### ISSUE TITLE
slides crash due to index out of range

### ISSUE THREAD

**Issue by i3d** [maaslalani/slides#74] opened 2021-07-05 22:02 UTC
**Describe the bug**

input md file:

```
# example complicate cargo workspace hierarchy.

## [link1](https://i.imgur.com/npGGJBQ.png)

## [link2](https://learning-rust.github.io/docs/a4.cargo,crates_and_basic_project_structure.html)
```

**To Reproduce**
1.  create a md file with the above content.
2. run `slides foo.md`
3.  See the crash.

**Expected behavior**
the program shouldn't crash.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 11.4
 - Version [e.g. 22]  slides 0.40

**Additional context**
Caught panic:

runtime error: index out of range [0] with length 0

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack(0x5b, 0x0, 0x0)
        runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x25
github.com/charmbracelet/bubbletea.(*Program).Start.func2(0xc0004fc120)
        github.com/charmbracelet/bubbletea@v0.14.0/tea.go:447 +0xd6
panic(0x15e1700, 0xc000016d38)
        runtime/panic.go:965 +0x1b9
github.com/maaslalani/slides/internal/model.Model.View(0xc00034f290, 0x0, 0x0, 0x0, 0xc0000162a0, 0x11, 0xc0006d0a16, 0xa, 0xc00030a0e0, 0x7ffeefbfbdb7, ...)
        github.com/maaslalani/slides/internal/model/model.go:138 +0x51e
github.com/charmbracelet/bubbletea.(*Program).Start(0xc0004fc120, 0x0, 0x0)
        github.com/charmbracelet/bubbletea@v0.14.0/tea.go:491 +0x331
github.com/maaslalani/slides/cmd.glob..func1(0x1d6f640, 0xc00034f100, 0x1, 0x1, 0x0, 0x0)
        github.com/maaslalani/slides/cmd/root.go:44 +0x209
github.com/spf13/cobra.(*Command).execute(0x1d6f640, 0xc0001ac010, 0x1, 0x1, 0x1d6f640, 0xc0001ac010)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x1d6f640, 0xc000000180, 0x200000003, 0xc000000180)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/maaslalani/slides/cmd.Execute()
        github.com/maaslalani/slides/cmd/root.go:50 +0x31
main.main()
        github.com/maaslalani/slides/main.go:8 +0x25

**Comment by maaslalani** [comment] 2021-07-05 22:06
I believe I fixed this in https://github.com/maaslalani/slides/releases/tag/v0.4.1

**Comment by maaslalani** [comment] 2021-07-07 01:56
I tried this on latest and could not reproduce, going to close this issue.
![image](https://user-images.githubusercontent.com/42545625/124688609-0df40c80-dea5-11eb-96cb-cf917faa8b1c.png)

**Closed by maaslalani** 2021-07-07 01:56 UTC
