### ISSUE TITLE
graph-easy doesn't work

### ISSUE THREAD

**Issue by airtonix** [maaslalani/slides#168] opened 2022-06-23 23:54 UTC
https://user-images.githubusercontent.com/61225/175433829-90b402ce-7673-4fe4-8e8a-4d0dee827ba8.mp4

```
System:
    OS: Linux 5.18 Fedora Linux 35 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 24.64 GB / 31.10 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.7.1 - ~/.asdf/installs/nodejs/17.7.1/bin/node
    Yarn: 1.22.15 - ~/.asdf/installs/nodejs/17.7.1/bin/yarn
    npm: 8.5.2 - ~/.asdf/installs/nodejs/17.7.1/bin/npm
  Managers:
    pip3: 22.1.2 - ~/.asdf/shims/pip3
    Yum: 4.13.0 - /usr/bin/yum
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 11.3.1 - /usr/lib64/ccache/gcc
    Git: 2.35.3 - /usr/bin/git
    FFmpeg: 4.4.2 - /usr/bin/ffmpeg
  Servers:
    Apache: 2.4.53 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.14 - /usr/bin/docker
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
  IDEs:
    Nano: 5.8 - /usr/bin/nano
    Sublime Text: 4134 - /usr/bin/subl
    VSCode: 1.67.2 - /usr/bin/code
  Languages:
    Bash: 5.1.8 - /usr/bin/bash
    Go: 1.18 - /home/zenobius/.asdf/shims/go
    Java: 1.8.0_322 - /home/zenobius/.asdf/shims/javac
    Perl: 5.34.1 - /usr/bin/perl
    Python: 3.9.5 - /home/zenobius/.asdf/shims/python
    Python3: 3.9.5 - /home/zenobius/.asdf/shims/python3
  Databases:
    PostgreSQL: 13.4 - /usr/bin/postgres
    SQLite: 3.36.0 - /usr/bin/sqlite3
  Browsers:
    Brave Browser: 100.1.37.116
    Chrome: 101.0.4951.41
    Firefox: 101.0.1

```

**Comment by maaslalani** [comment] 2022-06-24 00:00
Hi, is the slides file executable?

```
chmod +x slides.md
```

**Comment by rspi** [comment] 2022-06-28 07:52
I'm having the same issue. File is executable.

**Comment by maaslalani** [comment] 2022-07-03 21:52
Is `graph-easy` installed on your machine? And, are you on latest `slides@master`?

I am unable to reproduce: 
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/42545625/177058399-aa98cc3a-365e-4844-9dea-1b7e2419f75d.png">

**Comment by hackedhead** [comment] 2022-07-14 05:05
Pretty sure this is a function of being installed via snap.

if you try

```
~~~echo /etc/os-release
~~~~
```
 in your `slides.md`, you'll see the snap's ubnutu version, not your actual OS (Fedora)


It took me the last hour to figure that out. I wanted to use cowsay/figlet in my preprocess, but I guess I'd have to install slides _not_ via snapd to get access to tools on my host system.

**Comment by draxil** [comment] 2022-07-28 15:42
I got it working in my case. One tip to people struggling with this if you don't have anything on the line after the command, say:
```
~~~cat /etc/os-release
~~~
```
it doesn't match, you need at least:
```
~~~cat /etc/os-release

~~~
```

**Comment by hackedhead** [comment] 2022-07-28 15:48
> @hackedhead I think you mean cat there and not echo?
> 
Good catch, yes

**Comment by dlvhdr** [comment] 2022-08-08 15:50
@maaslalani, any idea how to install this on a mac?

**Comment by draxil** [comment] 2022-08-08 15:57
@dlvhdr slightly off topic :D 

but there's mac instructions in the readme, both homebrew:
`brew install slides`
and using go:
`go install github.com/maaslalani/slides@latest`

**Comment by maaslalani** [comment] 2022-08-08 15:58
@draxil I think he meant `graph-easy` but correct me if I'm wrong @dlvhdr

**Comment by draxil** [comment] 2022-08-08 16:00
@dlvhdr oh sorry you're talking about Graph Easy aren't you.. Silly me:

```brew install cpanminus
cpan Graph::Easy```

**Comment by dlvhdr** [comment] 2022-08-08 16:07
Yes thank you!

**Comment by maaslalani** [comment] 2022-08-08 16:11
Going to close this issue as it seems to be a symptom of installing via the `snap` package manager and not a bug in `slides` itself.

**Closed by maaslalani** 2022-08-08 16:11 UTC

**Comment by airtonix** [comment] 2022-08-11 00:41
Sorry, no i didn't install via snap. I never use snap... because i'm on Fedora.

**Comment by airtonix** [comment] 2022-08-11 01:05
edit: I forget why i even made this ticket, but in my recent example you can see that the first example of a graph doesn't work (but for some reason in my first video example is does work)


Actually.. no i remember;

Looks like you have a code block that defines how the diagram should be drawn and the second is actually just a bitmap image.

In both cases, the code block either: 
- just renders as a codeblock, or
- doesn't render at all

**Comment by airtonix** [comment] 2022-08-11 01:13
I'm not sure where we've suggest that `/etc/os-release` will work since on fedora it's not a binary: 

```shell
> cat /etc/os-release 
NAME="Fedora Linux"
VERSION="36 (Workstation Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```


so in the slide it has to be : 


    ```shell
    ~~~cat /etc/os-release
    
    ~~~
    ```

which results in: 

![image](https://user-images.githubusercontent.com/61225/184048749-c1365504-0a08-40e2-b70f-7d6e3c4ca7fc.png)

**Comment by draxil** [comment] 2022-08-11 04:55
@airtonix does the graph-easy command work for you *outside* of slides?

**Comment by airtonix** [comment] 2022-08-11 21:42
@draxil My issue was that I did not have graph-easy installed.

The solution is clearer documentation.

I'll open a PR over the next couple days to help improve instructions in that regard. 

👍🏻
