### ISSUE TITLE
(Sixel) image display support

### ISSUE THREAD

**Issue by christianparpart** [maaslalani/slides#195] opened 2022-10-31 09:30 UTC
**Is your feature request related to a problem? Please describe.**

Yes. I'd like to be able to design a graphviz .dot file. Ideally only that, and have that being automatically displayed as graphical version in the slides. you can use the graphviz's dot tool to convert to png, which in turn can be converted to Sixel (there seem to be even Golang-sixel packages available already). So writing .dot file inline in my presentation and have it displayed properly graphed would be awesome.

**Describe the solution you'd like**

Given the possibility to write my digraph in my .md file, I want `slides` to transform that to sixel and render it inline in the terminal. support for sixel can be discovered at runtime, so a fallback to, say, boxart could be implemented optionally.

**Describe alternatives you've considered**
There's no alternative except not using `slides`, which would be sad :)

**Additional context**

I want to use `slides` to create a series of slides I can talk along with to share some knowledge (terminal stuff, actually, so using `slides` would just be natural :) )

**Comment by christianparpart** [comment] 2022-10-31 10:02
NB: I tried preprocessing, but that seems to fitler out control codes (most importantly 0x1B escape character). So I cannot inject custom VT sequences to work around such limitation.

**Comment by maaslalani** [comment] 2022-11-04 20:34
Hey, I believe this is a duplicate of #2 (feel free to reopen if I am mistaken)

**Closed by maaslalani** 2022-11-04 20:34 UTC
